### ISSUE TITLE
Error running create_soilproperties.R

### ISSUE THREAD

**Issue by wuesh** [NCAR/wrf_hydro_model_tools#32]
Hello, everyone! 
When I run the create_soilproperties.R script, I follow the documentation to put the input file in the same directory as the R script. "Error in nc_open trying to open file soil_properties.nc (return_on_error= FALSE)" is displayed. The reason should be that there are no hydro2dtbl.nc and soil_properties.nc files. I tried to put the two NC files from wrf-hydro's example_case into the directory, but I still got "Error in ncvar_add, defining var smcref", "Error in ncvar_add, defining var SMCMAX1" indicates that the updated NC data does not coincide with the fields in the geo_em.d01.nc file, and an error occurs when wrf-hydro is run. "WARNING: Unable to open LAND Spatial Metadata file. Defaulting to missing values."
I don't know what went wrong with my operation. I am looking forward to your reply. Any help will be greatly appreciated.

**Comment by wuesh** [comment]
[create-soilproperties.zip](https://github.com/user-attachments/files/16557921/create-soilproperties.zip)
![2024-08-09 154920](https://github.com/user-attachments/assets/40751376-4681-4e06-8574-9f4d76bab218)
these are my input file,thank you!

**Comment by aubreyd** [comment]
I'm not quite following - the create_soilproperties.R script should create those 2 files (soil_properties.nc and hydro2dtbl.nc). You should provide a path to the geo_em file and the TBL input files, then paths to where you want the script to create the 2 output files.

There may be a conflict between more recent versions of R/ncdf4. Please try this update if you are getting output variables with -9999/fill values.

https://github.com/aubreyd/wrf_hydro_model_tools/tree/main/parameters/create_soilproperties

**Comment by wuesh** [comment]
> I'm not quite following - the create_soilproperties.R script should create those 2 files (soil_properties.nc and hydro2dtbl.nc). You should provide a path to the geo_em file and the TBL input files, then paths to where you want the script to create the 2 output files.
> 
> There may be a conflict between more recent versions of R/ncdf4. Please try this update if you are getting output variables with -9999/fill values.
> 
> https://github.com/aubreyd/wrf_hydro_model_tools/tree/main/parameters/create_soilproperties
Thank you for your reply, but after I modified the input path and output path of create_soilproperties.R script, I still got an error: "Error in nc_open trying to open file D:/WRF-Hydro/R/create-soilproperties/soil_properties.nc (return_on_error= FALSE )", I notice the error is in "ncid < -nc_open (slpropFile, write=TRUE)", but I can't provide the soil_properties.nc and hydro2dtbl.nc files that match domain. This confused me, "nc_open" should just open an existing NC file, not create a new NC file.
Look forward to your reply again, thank you!
![Uploading 2024-08-10 163146.png…]()

**Comment by aubreyd** [comment]
The script will create the soil_properties.nc and hydro2dtbl.nc files. They should not exist before running the script. Make sure you have write permission to the path you provide.
